version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: bitriseio/android-ndk:v2017_11_04-07_00-b753
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Add Android SDK licenses
          command: mkdir -p $ANDROID_HOME/licenses/ && printf "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
      - run:
          name: Install file (https://github.com/android-ndk/ndk/issues/188)
          command: sudo apt-get install file
      - run:
          name: Download submodules
          command: git submodule update --init --recursive
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon 
      - run:
          name: Build app
          command: ./gradlew assembleDebug assembleDebugProguarded --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./unittests.sh
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Upload test results to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: Play store deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [[ $CIRCLE_TAG ]]; then
              cd app
              openssl aes-256-cbc -K $KEY -iv $IV -in secrets.tar.enc -out secrets.tar -d
              tar xvf secrets.tar
              cd ..
              ./gradlew publishPlayRelease --no-daemon
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
